### PR TITLE
API v2

### PR DESCRIPTION
**Pull request by geophree**
This pull request is ready to be merged.  Thoughts?

/cc @dbellizzi @BorePlusPlus

### CODE REVIEW

**Comment by geophree** [comment]
I fixed the cycle detection, and we can merge this whenever we want to.

There are two other things that we might want to add:
* Support for passing in a `context` object to `system.start()` to fill in any gaps in its components, e.g. nested non-fully defined systems.
* Support for generator functions (instead of objects with `start` and/or `stop` methods) that yield two promises (for async, or just normal values for non-async), one for component start, one for stop.

**Comment by geophree** [comment]
re: passing a `context` to `system.start()`:  we could even have it override the existing component so systems could supply an overridable default.  The passed-in `context` components would be assumed to have started already, and to be stopped outside our system (I suppose we wouldn't even have access to their `start`/`stop` anyway).

**Comment by geophree** [comment]
I've just added support for passing `context` to `system.start()`, and it overrides components.  Also, this allows for nested systems with dependencies.

**Comment by geophree** [comment]
My most recent commit adds support for simple function and generator components. e.g.:
```js
// useful for things that don't need teardown (refdata?)
export function functionComponent(context) {
  // Do some sync setup with context.dep and context.end
  return asyncOrSyncFunction(context.dep);
}
functionComponent.dependencies = ['dep', 'end'];

export function *generatorComponent(context) {
  // Do some sync setup with context.dep and context.end
  yield asyncOrSyncStartupFunction(context.dep);
  // Do some sync teardown with context.dep and context.end
  yield asyncOrSyncStopFunction(context.end);
}
generatorComponent.dependencies = ['dep', 'end'];
```

**Comment by BorePlusPlus** [comment]
I was thinking of doing something similar. Would you care to give me a quick walk-through when you can spare the moment (just ping me on hipchat)? Ditching toposort made things slightly more complex (state management).

I quite like how @sithmel decided to move dependency declaration out of components into wiring. See end of [functions to services](https://github.com/sithmel/diogenes#from-functions-to-services) section for how that looks.  
I like how it makes dependency graph easy to see at a glance, on the other hand it does mean that implementers need to repeat the same deps every time.

What are the ideas regarding existing electric components? Some kind of shimming or just plain rewrites?

**Comment by geophree** [comment]
The wiring is a bit more obvious that way, but I'm a big fan of DRY, and this just makes it harder for people to use the components.  They have to know what the component needs either way (to make sure they provide everything in their system), so we've already broken encapsulation.  However, if we don't force them to define wiring, we could conceivably define defaults somehow so that people maybe wouldn't need to know the deps to use the components.

**Comment by geophree** [comment]
* `prepareComponent`: used to wire up the promise chains, it gives you:
  * `promise`: will be fulfilled/rejected based on the components (un)successful completion of `start`/`stop`
  * `exec`: used to execute the component (passed the contex)
* `makeDepsPromise`: wires up all the promises the component is dependent on into one Promise.all

**Comment by gabceb** [comment]
I hope this is a major version bump. Having to rewrite old electrician service is a bad idea IMO

I +1 @BorePlusPlus comment of preferring the simple implementation. Would it be possible to split this PR into a promises one and the cycle detection work? It seems that the latter is what made everything more complicated but i may be wrong.

**Comment by geophree** [comment]
Definitely a major version bump.

The rewrite is what made it complicated, and lost cycle detection.  The cycle detection is now a separate thing entirely.

**Comment by geophree** [comment]
Now system deps that are missing are re-exported on `system.dependencies` so we can define incomplete systems (without defaults) and compose them as long as we eventually supply all the deps from some encompassing system.  I'm feeling pretty good about this new api. :laughing: :rocket: :tada:

**Comment by rouanw** [comment]
I'm afraid this Pull Request has gone a bit stale over time and there are no current plans to update the electrician API. Closing for now.

**Pull request closed without merging**
