### PR TITLE
Lint like bosco

### PR DESCRIPTION
**Pull request by geophree**
* Add linting rules like tes/bosco and update the code to conform to them.
* Increase the test coverage threshold to 100%.
* Add pre-commit triggers to run lint and tests

No functional changes.

### CODE REVIEW

**Comment by BorePlusPlus** [comment]
:+1:

Couple of opinions:
* I quite like 4 rather than 2 space indentation. When your code is overly complexr 2 spaces just hide the visual side of it.
* I quite like a space after function keyword (no matter if followed by name or not).

I would prefer if we could use these rules, on the other hand I understand that there is a drive to homogenise our code base. These are my preferences, but I am not ideologically attached to them. So I leave the decision up to you: You can indulge the old man (me) and take notice of my preferences, or if you feel strongly enough that uniformity is something we should be striving for, just say so and I'll pull.

**Comment by geophree** [comment]
I probably prefer 2 spaces (I'd go for tabs if I thought people could actually do it) about as much as you prefer 4, but I think we should go with 2 for consistency.  Same with function spacing, although that gets taken care of if we move to ES6.

**Comment by BorePlusPlus** [comment]
OK sir, I stand by my words. You said it and I'm pulling it.

**Comment by geophree** [comment]
Thanks. :+1:

**Comment by gabceb** [comment]
A moment of silence for all the deleted space characters...

**Comment by BorePlusPlus** [comment]
> A moment of silence for all the deleted space characters...

:sob:

**Pull request merged**
